apiVersion: apps/v1
kind: Deployment
metadata:
  name: civil-judgments-api
  labels:
    app: civil-judgments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: civil-judgments-api
  template:
    metadata:
      labels:
        app: civil-judgments-api
    spec:
      containers:
        - name: civil-judgments-api
          image: ghcr.io/tyler-harpool/poc-ocfs/civil_judgments_api:latest
          ports:
            - containerPort: 3004
          env:
            - name: DATABASE_URL
              value: "postgres://app_user:dev_only_pwd@postgres-service:5432/app_db"
