apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patch-deployment.yaml

# Environment specific configurations
configMapGenerator:
  - name: adr-api-prod-config
    literals:
      - LOG_LEVEL=error
