apiVersion: apps/v1
kind: Deployment
metadata:
  name: adr-api
spec:
  template:
    spec:
      containers:
        - name: adr-api
          image: ghcr.io/tyler-harpool/poc-ocfs/adr_api:main@sha256:593941650f6a6e04abbabeab58b816ea82a598be7efd0c64dbdc4ad724e6858a
