apiVersion: apps/v1
kind: Deployment
metadata:
  name: charges-api
  labels:
    app: charges-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charges-api
  template:
    metadata:
      labels:
        app: charges-api
    spec:
      containers:
        - name: charges-api
          image: ghcr.io/tyler-harpool/poc-ocfs/charges_api:latest
          ports:
            - containerPort: 3003
          env:
            - name: DATABASE_URL
              value: "postgres://app_user:dev_only_pwd@postgres-service:5432/app_db"
