apiVersion: v1
kind: Service
metadata:
  name: attorney-advocate-api
spec:
  selector:
    app: attorney-advocate-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
