apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-permanency-api
  labels:
    app: dependency-permanency-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dependency-permanency-api
  template:
    metadata:
      labels:
        app: dependency-permanency-api
    spec:
      containers:
        - name: dependency-permanency-api
          image: ghcr.io/tyler-harpool/poc-ocfs/dependency_permanency_api:latest
          ports:
            - containerPort: 3006
          env:
            - name: DATABASE_URL
              value: "postgres://app_user:dev_only_pwd@postgres-service:5432/app_db"
