apiVersion: v1
kind: Service
metadata:
  name: dependency-permanency-api
spec:
  selector:
    app: dependency-permanency-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3006
  type: ClusterIP
