apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/tyler-harpool/k8-ocfs.git
        revision: HEAD
        directories:
          - path: apps/*/overlays
  template:
    metadata:
      name: 'core-applications'
    spec:
      project: default
      source:
        repoURL: https://github.com/tyler-harpool/k8-ocfs.git
        targetRevision: HEAD
        path: '{{path}}/dev'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'dev'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true