apiVersion: apps/v1
kind: Deployment
metadata:
  name: sanctions-api
  labels:
    app: sanctions-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sanctions-api
  template:
    metadata:
      labels:
        app: sanctions-api
    spec:
      containers:
        - name: sanctions-api
          image: ghcr.io/tyler-harpool/poc-ocfs/sanctions_api:latest
          ports:
            - containerPort: 3015
          env:
            - name: DATABASE_URL
              value: "postgres://app_user:dev_only_pwd@postgres-service:5432/app_db"
