apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  labels:
    app: gateway-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 8000
  selector:
    app: gateway-api
