apiVersion: apps/v1
kind: Deployment
metadata:
  name: adr-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adr-api
  template:
    metadata:
      labels:
        app: adr-api
    spec:
      containers:
        - name: adr-api
          image: ghcr.io/tyler-harpool/poc-ocfs/adr_api:main@sha256:593941650f6a6e04abbabeab58b816ea82a598be7efd0c64dbdc4ad724e6858a
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: url
