apiVersion: apps/v1
kind: Deployment
metadata:
  name: diversion-api
  labels:
    app: diversion-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diversion-api
  template:
    metadata:
      labels:
        app: diversion-api
    spec:
      containers:
        - name: diversion-api
          image: ghcr.io/tyler-harpool/poc-ocfs/diversion_api:latest
          ports:
            - containerPort: 3005
          env:
            - name: DATABASE_URL
              value: "postgres://app_user:dev_only_pwd@postgres-service:5432/app_db"
