apiVersion: apps/v1
kind: Deployment
metadata:
  name: participants-api
  labels:
    app: participants-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participants-api
  template:
    metadata:
      labels:
        app: participants-api
    spec:
      containers:
        - name: participants-api
          image: ghcr.io/tyler-harpool/poc-ocfs/participants_api:latest
          ports:
            - containerPort: 3010
          env:
            - name: DATABASE_URL
              value: "postgres://app_user:dev_only_pwd@postgres-service:5432/app_db"
